# Generated by Django 3.2.7 on 2021-11-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211104_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='surname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
