# Generated by Django 3.2.9 on 2021-11-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='dato_of_birth',
            new_name='date_of_birth',
        ),
    ]
