# Generated by Django 3.2.9 on 2021-11-21 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_alter_userdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('user_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL)),
                ('user_requesting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_requesting', 'user_requested')},
            },
        ),
    ]
