# Generated by Django 3.2.9 on 2021-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0002_usermovieseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='is_imdb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movieseries',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
