# Generated by Django 3.2.9 on 2021-11-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0003_auto_20211128_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
    ]
