# Generated by Django 3.2.9 on 2021-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0004_movieseries_is_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='foreign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
