# Generated by Django 3.2.9 on 2021-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0005_movieseries_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
    ]
