# Generated by Django 3.2.9 on 2021-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0006_movieseries_is_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='foreign_id',
            field=models.CharField(max_length=100),
        ),
    ]
