# Generated by Django 3.2.9 on 2021-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0007_alter_movieseries_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieseries',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='usermovieseries',
            name='watched_at',
            field=models.DateTimeField(null=True),
        ),
    ]
