# Generated by Django 3.2.9 on 2021-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0008_auto_20211129_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='foreign_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
