# Generated by Django 3.2.9 on 2021-12-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0009_alter_movieseries_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/communicationlog/%Y/%m/%d/'),
        ),
    ]
