# Generated by Django 3.2.9 on 2021-12-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0010_movieseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieseries',
            name='foreign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermovieseries',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
