# Generated by Django 3.2.9 on 2021-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0012_alter_movieseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='image',
            field=models.ImageField(default=1, upload_to='frontend/static/images'),
            preserve_default=False,
        ),
    ]
