# Generated by Django 3.2.9 on 2021-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseriescollection', '0016_alter_movieseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
